# Generated by Django 6.0.2 on 2026-02-04 09:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api', 'OCDSReleases API'), ('bulk', 'Bulk file import')], max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('items_ingested', models.PositiveIntegerField(default=0)),
                ('items_failed', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcuringEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('contact_name', models.CharField(blank=True, max_length=256)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.CharField(max_length=256, unique=True)),
                ('ocid', models.CharField(db_index=True, max_length=256)),
                ('date', models.DateTimeField()),
                ('tag', models.JSONField(blank=True, default=list)),
                ('initiation_type', models.CharField(blank=True, max_length=64)),
                ('raw_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('registration_number', models.CharField(blank=True, max_length=64)),
                ('bbbee_level', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('province', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('preferred_cpvs', models.JSONField(blank=True, default=list)),
                ('preferred_buyers', models.JSONField(blank=True, default=list)),
                ('min_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('max_value', models.DecimalField(decimal_places=2, default=100000000, max_digits=18)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('whatsapp_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('release_id', models.CharField(blank=True, max_length=256)),
                ('message', models.TextField()),
                ('payload_snippet', models.TextField(blank=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='ocds.ingestionrun')),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.CharField(max_length=128, unique=True)),
                ('ocid', models.CharField(db_index=True, max_length=256)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('planning', 'Planning'), ('planned', 'Planned')], db_index=True, default='active', max_length=32)),
                ('category', models.CharField(blank=True, max_length=256)),
                ('additional_procurement_categories', models.JSONField(blank=True, default=list)),
                ('province', models.CharField(blank=True, db_index=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('value_amount', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=18, null=True)),
                ('value_currency', models.CharField(default='ZAR', max_length=8)),
                ('tender_start_date', models.DateTimeField(blank=True, null=True)),
                ('tender_end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cpv_codes', models.JSONField(blank=True, default=list)),
                ('submission_methods', models.JSONField(blank=True, default=list)),
                ('match_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procuring_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='ocds.procuringentity')),
                ('release', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tender', to='ocds.release')),
            ],
        ),
        migrations.CreateModel(
            name='SavedTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('calendar_added', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tenders', to='ocds.supplierprofile')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='ocds.tender')),
            ],
            options={
                'unique_together': {('supplier', 'tender')},
            },
        ),
        migrations.CreateModel(
            name='TenderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=128)),
                ('document_type', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=512)),
                ('url', models.URLField(max_length=1024)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=128)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ocds.tender')),
            ],
            options={
                'unique_together': {('tender', 'document_id')},
            },
        ),
    ]
