# Generated by Django 6.0.2 on 2026-02-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocds', '0002_supplierprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
